import logging
import random
import warnings

import pytest

logger = logging.getLogger()


@pytest.fixture()
def regex():
    return r"""  *->"""


def test_0_regex_single(regex):
    print("Pre-foldy stuff...")
    print("Test Pass 1!")
    print(regex)
    print("More pre-foldy stuff...")
    print("This line marks the middle of the RegEx fold.")
    print(regex)
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print("Middle of the foldy stuff...")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("Middle of the foldy stuff...")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("Middle of the foldy stuff...")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("Middle of the foldy stuff...")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("Post-foldy stuff...")
    print("More post-foldy stuff...")
    assert True


def test_0_regex_double(regex):
    print("Pre-foldy stuff...")
    print("Test Pass 1!")
    print(regex)
    print("More pre-foldy stuff...")
    print(f"​​​This line marks the beginning of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print(regex)
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print(regex)
    print("Middle of the foldy stuff...")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print("Middle of the foldy stuff...")
    print("This line marks the middle of the RegEx fold.")
    print("This line marks the middle of the RegEx fold.")
    print(f"￼​This line marks the end of the RegEx fold.")
    print("Post-foldy stuff...")
    print("More post-foldy stuff...")
    assert True


def test_0_regex_logs():
    print("This line is DEBUG level.")
    print("This line is INFO level.")
    print("This line is WARNING level.")
    print("This line is ERROR level.")
    print("This line is CRITICAL level.")
    print("This line is NOT ANY level.")
    print("This line is DEBUG level #1.")
    print("This line is DEBUG level #2.")
    print("This line is DEBUG level #3.")
    print("This line is DEBUG level #4.")
    print("This line is DEBUG level #5.")
    print("This line is NOT ANY level.")
    print("This line is INFO level #1.")
    print("This line is INFO level #2.")
    print("This line is INFO level #3.")
    print("This line is DEBUG level #1.")
    print("This line is DEBUG level #2.")
    print("This line is DEBUG level #3.")
    print("This line is NOT ANY level.")
    print("This line is WARNING level #1.")
    print("This line is WARNING level #2.")
    print("This line is WARNING level #3.")
    print("This line is INFO level #1.")
    print("This line is INFO level #2.")
    print("This line is INFO level #3.")
    print("This line is DEBUG level #1.")
    print("This line is DEBUG level #2.")
    print("This line is DEBUG level #3.")
    print("This line is NOT ANY level.")
    assert True


def test_0_regex_logs_firstline():
    print("This line is DEBUG level.")
    print("This line is INFO level.")
    print("This line is WARNING level.")
    print("This line is ERROR level.")
    print("This line is CRITICAL level.")
    print("This line is NOT ANY level.")
    print("This line is DEBUG level #1.")
    print("This line is DEBUG level #2.")
    print("This line is DEBUG level #3.")
    print("This line is DEBUG level #4.")
    print("This line is DEBUG level #5.")
    print("This line is NOT ANY level.")
    print("This line is INFO level #1.")
    print("This line is INFO level #2.")
    print("This line is INFO level #3.")
    print("This line is DEBUG level #1.")
    print("This line is DEBUG level #2.")
    print("This line is DEBUG level #3.")
    print("This line is NOT ANY level.")
    print("This line is WARNING level #1.")
    print("This line is WARNING level #2.")
    print("This line is WARNING level #3.")
    print("This line is INFO level #1.")
    print("This line is INFO level #2.")
    print("This line is INFO level #3.")
    print("This line is DEBUG level #1.")
    print("This line is DEBUG level #2.")
    print("This line is DEBUG level #3.")
    print("This line is NOT ANY level.")

    print("DEBUG level.")
    print("INFO level.")
    print("WARNING level.")
    print("ERROR level.")
    print("CRITICAL level.")
    print("NOT ANY level.")
    print("DEBUG level #1.")
    print("DEBUG level #2.")
    print("This line is DEBUG level #3.")
    print("DEBUG level #4.")
    print("DEBUG level #5.")
    print("NOT ANY level.")
    print("INFO level #1.")
    print("This line is INFO level #2.")
    print("This line is INFO level #3.")
    print("DEBUG level #1.")
    print("DEBUG level #2.")
    print("This line is DEBUG level #3.")
    print("This line is NOT ANY level.")
    print("This line is WARNING level #1.")
    print("This line is WARNING level #2.")
    print("This line is WARNING level #3.")
    print("This line is INFO level #1.")
    print("This line is INFO level #2.")
    print("This line is INFO level #3.")
    print("This line is DEBUG level #1.")
    print("DEBUG level #2.")
    print("DEBUG level #3.")
    print("This line is NOT ANY level.")
    assert True
